---
apiVersion: v1
kind: Pod
metadata:
  name: my-main-app
spec:
  containers:
    - image: nginx
      name: main
      env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: sample-config-map
              key: username
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sample-config-map
              key: password

              