apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinity-demo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: numberOfCores
                operator: Gt
                values: [ "2" ]
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchFields:
              - key: 'diskType'
                operator: In
                values: ["ssd"]
  containers:
    - name: nodeaffinity-container
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet: 
          port: 80
          path: /
        initialDelaySeconds: 30
     