kind: Service
apiVersion: v1
metadata:
  name: service-example
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer