---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-ec2-service
subsets:
  - addresses:
      - ip: 10.0.1.11
      - ip: 10.0.2.22
      - ip: 10.0.3.33
    ports:
      - port: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name: external-ec2-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80