apiVersion: v1
kind: Pod
metadata:
  name: liveness-demo
spec:
  containers:
    - name: liveness-container
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet: 
          port: 80
          path: /
        initialDelaySeconds: 30
