apiVersion: v1
kind: Pod
metadata:
  name: liveness-fail-demo
spec:
  containers:
    - name: liveness-fail-container
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet: 
          port: 8080
          path: /
        initialDelaySeconds: 30
