route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
    - to: 'devops@qt.com'
      from: 'alerts@qt.com'
      smarthost: smtp.mailtrap.io:587
      auth_username: '597f05c4da05ed'
      auth_password: '5a5b4720cb7db8'
      auth_identity: '597f05c4da05ed'

- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']