---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - image: mysql
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: qwert456
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: mysql-store
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-store
      persistentVolumeClaim:
        claimName: mysqlclaim