---
apiVersion: v1
kind: Pod
metadata:
  name: secretvol-pod
spec:
  containers:
    - image: nginx
      name: app
      volumeMounts:
        - name: secret-volume
          mountPath: /var/secrets
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-creds
      