---
apiVersion: v1
kind: Pod
metadata:
  name: secretenv-pod
spec:
  containers:
    - image: nginx
      name: app
      envFrom:
        - secretRef:
            name: db-creds
        - secretRef:
            name: my-creds